---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: centos-7
    image: centos:7
  - name: almalinux-8
    image: almalinux:8
  - name: almalinux-9
    image: almalinux:9
  - name: rockylinux-8
    image: rockylinux:8
  - name: rockylinux-9
    image: rockylinux:9
  - name: debian-bookworm
    image: debian:bookworm
  - name: debian-bullseye
    image: debian:bullseye
  - name: ubuntu-22-04
    image: ubuntu:22.04
  - name: ubuntu-20-04
    image: ubuntu:20.04
provisioner:
  name: ansible
verifier:
  name: ansible
