---
name: build

on:
  push:
    branches:
      - master
      - release/v*
      - feature/*
      - hotfix/*
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@6.0.1
        with:
          command: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image:
          - centos:7
          - almalinux:8
          - almalinux:9
          - rockylinux:8
          - rockylinux:9
          - debian:bookworm
          - debian:bullseye
          - ubuntu:22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@6.0.0
        with:
          image: "${{ matrix.image }}"
          options: parallel
          scenario: my_specific_scenario